#:schema node_modules/wrangler/config-schema.json
name = "upload"
main = "src/index.ts"
compatibility_date = "2024-09-09"
compatibility_flags = ["nodejs_compat"]

[[r2_buckets]]
binding = 'ASSETS'
bucket_name = 'assets'
